#!/usr/bin/env python3
from train import Train
import sys

if __name__ == '__main__':
    print("Training Start.....\n\n")
    print("*******************************************************")
    print("*******************************************************")

    model_path = './output/drive_v1.h5'
    train = Train('./data/train/driving_log.csv', './data/train/', model_path,
                    bath_size=64, epochs=2)
    train.perform_training()

    print("*******************************************************")
    print("*******************************************************")
    print("Train end")
    sys.exit(0)