#!/usr/bin/env python3
from train import Train
import sys

if __name__ == '__main__':
    print("Training Start.....\n\n")
    print("*******************************************************")
    print("*******************************************************")

    opts = {
        'train_logs': './data/train/driving_log.csv',
        'train_data': './data/train/',
        'test_logs': './data/test/driving_log.csv',
        'test_data': './data/test/',
        'model_path': './output/model_v1.h5',
        'old_model_path': './output/model_v1.h5'
    }
    train = Train(opts, bath_size=512, epochs=6, flip_images=True, retrain=False)
    train.perform_training()

    print("*******************************************************")
    print("*******************************************************")
    print("Train end\n\n\n")


    print("*******************************************************")
    print("*******************************************************")
    print("Test Evaluation")

    train.evaluate_model_on_test()

    print("\n\n\n\n\n\n")
    sys.exit(0)